---
title: "DataIntergrationChallenge"
author: "Abbi Edwards"
date: "07/06/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(scater)
library(scran)
library(batchelor)
library(bluster)
library(tidyverse)
library(pheatmap)
library(clustree)
library(Cairo)
library(BiocSingular)
library(cowplot)

```

## Loading the data you need


```{r Load}

p.tsne <- readRDS("../Robjects/DataIntergration_p.tsne.rds")
mnn.out <- readRDS("../Robjects/DataIntergration_mnn.out.rds")

clusters.mnn <- readRDS("../Robjects/DataIntergration_clusters.mnn.rds")
linear_rescaled <- readRDS("../Robjects/DataIntergration_linear_rescaled.rds")
rescaled <- readRDS("../Robjects/DataIntergration_rescaled.rds")

```

## Challenge 1

Draw the TSNE for the fastmnn corrected data. Compare it with the uncorrected TSNE, what do you think?

```{r yourCode1}


```

## Challenge 2

Can you draw the heatmaps for the other samples and decide if you think the correction looks satisfactory?

```{r yourCode2}




```

